"""Tests for the genotype file parser."""

import pytest
import polars as pl

from app.services.parser import (
    ParseError,
    detect_chip_version,
    detect_format,
    extract_vcf_header_meta,
    infer_biological_sex,
    parse_23andme,
    parse_ancestrydna,
    parse_cgi,
    parse_genotype_file,
    parse_vcf,
)

# ---------------------------------------------------------------------------
# Synthetic test data
# ---------------------------------------------------------------------------

SAMPLE_23ANDME = """\
# This data file generated by 23andMe at: Mon Jan 06 2025
# rsid\tchromosome\tposition\tgenotype
rs4477212\t1\t82154\tAA
rs3094315\t1\t752566\tAG
rs3131972\t1\t752721\tGG
rs12124819\t1\t776546\tAA
rs11240777\t1\t798959\tAG
rs6681049\t1\t800007\tCC
"""

SAMPLE_23ANDME_WITH_NOCALLS = """\
# rsid\tchromosome\tposition\tgenotype
rs4477212\t1\t82154\tAA
rs100\t1\t100\t--
rs200\t1\t200\t00
rs300\t1\t300\tDD
rs301\t1\t301\tDI
rs3094315\t1\t752566\tAG
"""

SAMPLE_23ANDME_HAPLOID = """\
# rsid\tchromosome\tposition\tgenotype
rs4477212\t1\t82154\tA
rs3094315\t1\t752566\tG
"""

SAMPLE_ANCESTRYDNA = """\
#AncestryDNA raw data download
#rsid\tchromosome\tposition\tallele1\tallele2
rs4477212\t1\t82154\tA\tA
rs3094315\t1\t752566\tA\tG
rs3131972\t1\t752721\tG\tG
rs12124819\t1\t776546\tA\tA
"""

SAMPLE_VCF = """\
##fileformat=VCFv4.1
##source=test
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE1
1\t82154\trs4477212\tA\tG\t100\tPASS\t.\tGT:GQ\t0/1:99
1\t752566\trs3094315\tA\tG\t100\tPASS\t.\tGT:GQ\t0/1:99
1\t752721\trs3131972\tA\tG\t100\tPASS\t.\tGT:GQ\t1/1:99
"""

SAMPLE_VCF_PHASED = """\
##fileformat=VCFv4.1
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE1
chr1\t82154\trs4477212\tA\tG\t100\tPASS\t.\tGT\t0|1
"""

SAMPLE_VCF_MULTIALLELIC = """\
##fileformat=VCFv4.1
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE1
1\t82154\trs4477212\tA\tG,T\t100\tPASS\t.\tGT\t0/1
1\t752566\trs3094315\tA\tG\t100\tPASS\t.\tGT\t0/1
"""

# Haploid genotypes on sex chromosomes (male chrX/chrY)
SAMPLE_VCF_HAPLOID = """\
##fileformat=VCFv4.1
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE1
X\t43591036\trs6323\tG\tT\t40\tPASS\t.\tGT:GQ\t1:99
X\t100000\trs99999\tC\tA\t50\tPASS\t.\tGT:GQ\t0:99
1\t752566\trs3094315\tA\tG\t100\tPASS\t.\tGT:GQ\t0/1:99
"""

# Complete Genomics var-ASM format:
# - Two rows per diploid variant (one per allele)
# - 0-based half-open coordinates (begin+1 = 1-based position)
# - rsIDs in xRef column as "dbsnp.NNN:rsXXXXXX"
# Locus 10: homozygous alt T/T (both alleles are SNP)
# Locus 20: het allele1=A (SNP), allele2=ref G (no SNP row)
# Locus 30: het allele1=ref A (no SNP row), allele2=G (SNP)
# Locus 40: VQLOW — should be filtered out
SAMPLE_CGI = """\
#ASSEMBLY_ID\tGS00253-DNA_A01_200_37-ASM
#GENOME_REFERENCE\tNCBI build 37
#TYPE\tVAR-ANNOTATION
\t\t\t\t\t\t\t\t\t\t\t\t\t
>locus\tploidy\tallele\tchromosome\tbegin\tend\tvarType\treference\talleleSeq\tvarScoreVAF\tvarScoreEAF\tvarQuality\thapLink\txRef
10\t2\t1\tchr1\t21579\t21580\tsnp\tC\tT\t100\t100\tVQHIGH\t\tdbsnp.83:rs526642
10\t2\t2\tchr1\t21579\t21580\tsnp\tC\tT\t135\t135\tVQHIGH\t\tdbsnp.83:rs526642
20\t2\t1\tchr1\t23974\t23975\tsnp\tG\tA\t58\t58\tVQHIGH\t\tdbsnp.100:rs2748067;dbsnp.131:rs76046194
30\t2\t2\tchr19\t38231\t38232\tsnp\tA\tG\t112\t112\tVQHIGH\t\tdbsnp.86:rs806727
40\t2\t1\tchr1\t46669\t46670\tsnp\tA\tG\t45\t45\tVQLOW\t\tdbsnp.100:rs2548905
"""


# ---------------------------------------------------------------------------
# Format detection
# ---------------------------------------------------------------------------

class TestDetectFormat:
    def test_detects_23andme(self):
        lines = SAMPLE_23ANDME.split("\n")[:10]
        assert detect_format(lines) == "23andme"

    def test_detects_ancestrydna(self):
        lines = SAMPLE_ANCESTRYDNA.split("\n")[:10]
        assert detect_format(lines) == "ancestrydna"

    def test_detects_vcf(self):
        lines = SAMPLE_VCF.split("\n")[:10]
        assert detect_format(lines) == "vcf"

    def test_detects_cgi(self):
        lines = SAMPLE_CGI.split("\n")[:10]
        assert detect_format(lines) == "cgi"

    def test_raises_on_unknown(self):
        with pytest.raises(ParseError):
            detect_format(["some random text", "with no structure"])


# ---------------------------------------------------------------------------
# 23andMe parser
# ---------------------------------------------------------------------------

class TestParse23andMe:
    def test_basic_parsing(self):
        df = parse_23andme(SAMPLE_23ANDME)
        assert len(df) == 6
        assert df.columns == ["rsid", "chrom", "position", "allele1", "allele2"]

    def test_specific_variant(self):
        df = parse_23andme(SAMPLE_23ANDME)
        row = df.filter(pl.col("rsid") == "rs3094315")
        assert row["allele1"][0] == "A"
        assert row["allele2"][0] == "G"
        assert row["chrom"][0] == "1"
        assert row["position"][0] == 752566

    def test_homozygous(self):
        df = parse_23andme(SAMPLE_23ANDME)
        row = df.filter(pl.col("rsid") == "rs4477212")
        assert row["allele1"][0] == "A"
        assert row["allele2"][0] == "A"

    def test_filters_nocalls(self):
        df = parse_23andme(SAMPLE_23ANDME_WITH_NOCALLS)
        assert len(df) == 2
        rsids = df["rsid"].to_list()
        assert "rs4477212" in rsids
        assert "rs3094315" in rsids

    def test_haploid_genotype(self):
        df = parse_23andme(SAMPLE_23ANDME_HAPLOID)
        assert len(df) == 2
        row = df.filter(pl.col("rsid") == "rs4477212")
        assert row["allele1"][0] == "A"
        assert row["allele2"][0] == "A"

    def test_empty_file_raises(self):
        with pytest.raises(ParseError):
            parse_23andme("# comment only\n")

    def test_dtypes(self):
        df = parse_23andme(SAMPLE_23ANDME)
        assert df.schema["rsid"] == pl.Utf8
        assert df.schema["chrom"] == pl.Utf8
        assert df.schema["position"] == pl.Int64
        assert df.schema["allele1"] == pl.Utf8
        assert df.schema["allele2"] == pl.Utf8


# ---------------------------------------------------------------------------
# AncestryDNA parser
# ---------------------------------------------------------------------------

class TestParseAncestryDNA:
    def test_basic_parsing(self):
        df = parse_ancestrydna(SAMPLE_ANCESTRYDNA)
        assert len(df) == 4
        assert df.columns == ["rsid", "chrom", "position", "allele1", "allele2"]

    def test_specific_variant(self):
        df = parse_ancestrydna(SAMPLE_ANCESTRYDNA)
        row = df.filter(pl.col("rsid") == "rs3094315")
        assert row["allele1"][0] == "A"
        assert row["allele2"][0] == "G"
        assert row["position"][0] == 752566

    def test_empty_file_raises(self):
        with pytest.raises(ParseError):
            parse_ancestrydna("# comment only\n")


# ---------------------------------------------------------------------------
# VCF parser
# ---------------------------------------------------------------------------

class TestParseVCF:
    def test_basic_parsing(self):
        df = parse_vcf(SAMPLE_VCF)
        assert len(df) == 3

    def test_homref_filtered(self):
        """Hom-ref (0/0) variants are dropped — they carry no information."""
        vcf = """\
##fileformat=VCFv4.1
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE1
1\t100\trs100\tA\tG\t.\tPASS\t.\tGT\t0/0
1\t200\trs200\tC\tT\t.\tPASS\t.\tGT\t0/1
"""
        df = parse_vcf(vcf)
        assert len(df) == 1
        assert df["rsid"][0] == "rs200"

    def test_het(self):
        df = parse_vcf(SAMPLE_VCF)
        row = df.filter(pl.col("rsid") == "rs3094315")
        assert row["allele1"][0] == "A"
        assert row["allele2"][0] == "G"

    def test_homalt(self):
        df = parse_vcf(SAMPLE_VCF)
        row = df.filter(pl.col("rsid") == "rs3131972")
        assert row["allele1"][0] == "G"
        assert row["allele2"][0] == "G"

    def test_phased_genotype(self):
        df = parse_vcf(SAMPLE_VCF_PHASED)
        assert len(df) == 1
        row = df.row(0, named=True)
        assert row["allele1"] == "A"
        assert row["allele2"] == "G"
        # chr prefix should be stripped
        assert row["chrom"] == "1"

    def test_skips_multiallelic(self):
        df = parse_vcf(SAMPLE_VCF_MULTIALLELIC)
        assert len(df) == 1
        assert df["rsid"][0] == "rs3094315"

    def test_haploid_hemizygous_alt(self):
        """Hemizygous ALT on chrX (e.g. rs6323 MAOA in males) should be duplicated."""
        df = parse_vcf(SAMPLE_VCF_HAPLOID)
        row = df.filter(pl.col("rsid") == "rs6323")
        assert len(row) == 1
        assert row["allele1"][0] == "T"
        assert row["allele2"][0] == "T"
        assert row["chrom"][0] == "X"

    def test_haploid_hemizygous_ref_filtered(self):
        """Hemizygous REF on chrX (haploid 0 → 0/0) is filtered as hom-ref."""
        df = parse_vcf(SAMPLE_VCF_HAPLOID)
        row = df.filter(pl.col("rsid") == "rs99999")
        assert len(row) == 0

    def test_haploid_mixed_with_diploid(self):
        """Haploid and diploid calls in same VCF should both be parsed (hom-ref filtered)."""
        df = parse_vcf(SAMPLE_VCF_HAPLOID)
        assert len(df) == 2  # 1 haploid ALT + 1 diploid het (haploid REF filtered)

    def test_empty_file_raises(self):
        with pytest.raises(ParseError):
            parse_vcf("##fileformat=VCFv4.1\n#CHROM\tPOS\tID\n")


# ---------------------------------------------------------------------------
# Complete Genomics parser
# ---------------------------------------------------------------------------

class TestParseCGI:
    def test_basic_parsing(self):
        df = parse_cgi(SAMPLE_CGI)
        assert df.columns == ["rsid", "chrom", "position", "allele1", "allele2"]
        # 3 variants: locus 10 (hom), locus 20 (het a1), locus 30 (het a2)
        # Locus 40 filtered out (VQLOW)
        assert len(df) == 3

    def test_homozygous_alt(self):
        """Locus 10: both alleles are SNP T (ref C)."""
        df = parse_cgi(SAMPLE_CGI)
        row = df.filter(pl.col("rsid") == "rs526642")
        assert row["allele1"][0] == "T"
        assert row["allele2"][0] == "T"

    def test_het_allele1_only(self):
        """Locus 20: only allele 1 is a SNP (A), allele 2 should be ref (G)."""
        df = parse_cgi(SAMPLE_CGI)
        row = df.filter(pl.col("rsid") == "rs2748067")
        assert row["allele1"][0] == "A"
        assert row["allele2"][0] == "G"

    def test_het_allele2_only(self):
        """Locus 30: only allele 2 is a SNP (G), allele 1 should be ref (A)."""
        df = parse_cgi(SAMPLE_CGI)
        row = df.filter(pl.col("rsid") == "rs806727")
        assert row["allele1"][0] == "A"
        assert row["allele2"][0] == "G"

    def test_filters_vqlow(self):
        """Locus 40 is VQLOW and should be excluded."""
        df = parse_cgi(SAMPLE_CGI)
        assert df.filter(pl.col("rsid") == "rs2548905").height == 0

    def test_position_conversion(self):
        """CGI 0-based begin=21579 should become 1-based position=21580."""
        df = parse_cgi(SAMPLE_CGI)
        row = df.filter(pl.col("rsid") == "rs526642")
        assert row["position"][0] == 21580

    def test_chr_prefix_stripped(self):
        df = parse_cgi(SAMPLE_CGI)
        row = df.filter(pl.col("rsid") == "rs806727")
        assert row["chrom"][0] == "19"

    def test_extracts_first_rsid_from_multi(self):
        """xRef with multiple dbsnp entries should extract the first rsID."""
        df = parse_cgi(SAMPLE_CGI)
        # Locus 20 has "dbsnp.100:rs2748067;dbsnp.131:rs76046194"
        assert df.filter(pl.col("rsid") == "rs2748067").height == 1

    def test_empty_file_raises(self):
        with pytest.raises(ParseError):
            parse_cgi("#TYPE\tVAR-ANNOTATION\n>locus\tploidy\tallele\n")

    def test_dtypes(self):
        df = parse_cgi(SAMPLE_CGI)
        assert df.schema["rsid"] == pl.Utf8
        assert df.schema["chrom"] == pl.Utf8
        assert df.schema["position"] == pl.Int64
        assert df.schema["allele1"] == pl.Utf8
        assert df.schema["allele2"] == pl.Utf8


# ---------------------------------------------------------------------------
# Chip version detection
# ---------------------------------------------------------------------------

class TestExtractVcfHeaderMeta:
    def test_wgs_header_with_contigs_and_source(self):
        lines = ["##fileformat=VCFv4.2", "##source=HaplotypeCaller"]
        lines += [f"##contig=<ID=chr{i},length=100000>" for i in range(1, 25)]
        lines += ["#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE"]
        content = "\n".join(lines)
        meta = extract_vcf_header_meta(content)
        assert meta["contig_count"] == 24
        assert meta["has_wgs_source"] is True

    def test_minimal_header_no_contigs(self):
        content = "##fileformat=VCFv4.1\n#CHROM\tPOS\tID\n"
        meta = extract_vcf_header_meta(content)
        assert meta["contig_count"] == 0
        assert meta["has_wgs_source"] is False

    def test_non_wgs_source(self):
        content = "##fileformat=VCFv4.1\n##source=Illumina GenCall\n#CHROM\n"
        meta = extract_vcf_header_meta(content)
        assert meta["has_wgs_source"] is False

    def test_deepvariant_source(self):
        content = "##fileformat=VCFv4.2\n##source=DeepVariant-1.6.0\n#CHROM\n"
        meta = extract_vcf_header_meta(content)
        assert meta["has_wgs_source"] is True

    def test_beagle_imputation_detected(self):
        content = '##fileformat=VCFv4.2\n##source="beagle.25Nov19.28d.jar"\n#CHROM\n'
        meta = extract_vcf_header_meta(content)
        assert meta["is_imputed"] is True
        assert meta["has_wgs_source"] is False

    def test_minimac_imputation_detected(self):
        content = "##fileformat=VCFv4.2\n##source=Minimac4\n#CHROM\n"
        meta = extract_vcf_header_meta(content)
        assert meta["is_imputed"] is True

    def test_imp_info_flag_detected(self):
        content = (
            '##fileformat=VCFv4.2\n'
            '##INFO=<ID=IMP,Number=0,Type=Flag,Description="Imputed marker">\n'
            '#CHROM\n'
        )
        meta = extract_vcf_header_meta(content)
        assert meta["is_imputed"] is True

    def test_dr2_info_detected(self):
        content = (
            '##fileformat=VCFv4.2\n'
            '##INFO=<ID=DR2,Number=1,Type=Float,Description="Dosage R-Squared">\n'
            '#CHROM\n'
        )
        meta = extract_vcf_header_meta(content)
        assert meta["is_imputed"] is True

    def test_normal_wgs_not_imputed(self):
        content = "##fileformat=VCFv4.2\n##source=HaplotypeCaller\n#CHROM\n"
        meta = extract_vcf_header_meta(content)
        assert meta["is_imputed"] is False

    def test_gatk_not_imputed(self):
        content = "##fileformat=VCFv4.2\n##source=GATK\n#CHROM\n"
        meta = extract_vcf_header_meta(content)
        assert meta["is_imputed"] is False


class TestDetectChipVersion:
    def test_23andme_v5(self):
        assert detect_chip_version(950_000) == "23andme_v5"

    def test_ancestrydna_v2(self):
        assert detect_chip_version(350_000) == "ancestrydna_v2"

    def test_unknown(self):
        assert detect_chip_version(50) == "unknown"

    def test_wgs_high_count_no_meta_needed(self):
        assert detect_chip_version(4_500_000) == "wgs"

    def test_wgs_header_confirmed_with_contigs(self):
        meta = {"contig_count": 24, "has_wgs_source": False}
        assert detect_chip_version(1_800_000, vcf_meta=meta) == "wgs"

    def test_wgs_header_confirmed_with_source(self):
        meta = {"contig_count": 0, "has_wgs_source": True}
        assert detect_chip_version(1_500_000, vcf_meta=meta) == "wgs"

    def test_gap_without_meta_stays_unknown(self):
        assert detect_chip_version(1_800_000) == "unknown"

    def test_gap_with_weak_meta_stays_unknown(self):
        meta = {"contig_count": 5, "has_wgs_source": False}
        assert detect_chip_version(1_800_000, vcf_meta=meta) == "unknown"

    def test_below_floor_with_meta_not_promoted(self):
        meta = {"contig_count": 24, "has_wgs_source": True}
        assert detect_chip_version(60_000, vcf_meta=meta) == "unknown"


# ---------------------------------------------------------------------------
# Integration: parse_genotype_file
# ---------------------------------------------------------------------------

class TestParseGenotypeFile:
    def test_23andme_integration(self):
        df, fmt, chip = parse_genotype_file(SAMPLE_23ANDME)
        assert fmt == "23andme"
        assert len(df) == 6
        assert chip == "unknown"  # too few variants for chip detection

    def test_ancestrydna_integration(self):
        df, fmt, chip = parse_genotype_file(SAMPLE_ANCESTRYDNA)
        assert fmt == "ancestrydna"
        assert len(df) == 4

    def test_vcf_integration(self):
        df, fmt, chip = parse_genotype_file(SAMPLE_VCF)
        assert fmt == "vcf"
        assert len(df) == 3

    def test_cgi_integration(self):
        df, fmt, chip = parse_genotype_file(SAMPLE_CGI)
        assert fmt == "cgi"
        assert len(df) == 3

    def test_filters_indels_from_23andme(self):
        content = """\
# rsid\tchromosome\tposition\tgenotype
rs100\t1\t100\tAG
rs200\t1\t200\tDI
rs300\t1\t300\tAA
"""
        df, fmt, _ = parse_genotype_file(content)
        assert len(df) == 2


# ---------------------------------------------------------------------------
# Multi-VCF ZIP merge
# ---------------------------------------------------------------------------

import gzip as _gzip
import io
import zipfile

from app.services.analysis import _merge_multi_vcf_zip, _chr_sort_key


class TestChrSortKey:
    def test_chr1(self):
        assert _chr_sort_key("sample.chr1_imputed.vcf.gz") == 1

    def test_chr22(self):
        assert _chr_sort_key("sample.chr22_imputed.vcf.gz") == 22

    def test_chrX(self):
        assert _chr_sort_key("sample.chrX.imputed.vcf.gz") == 23

    def test_no_chr_pattern(self):
        assert _chr_sort_key("random_file.vcf.gz") == 99


class TestMergeMultiVcfZip:
    VCF_HEADER = (
        "##fileformat=VCFv4.2\n"
        '##source="beagle.25Nov19.28d.jar"\n'
        "#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n"
    )
    CHR1_DATA = "1\t100\trs1\tA\tG\t.\tPASS\t.\tGT\t0/1\n1\t200\trs2\tC\tT\t.\tPASS\t.\tGT\t1/1\n"
    CHR2_DATA = "2\t100\trs3\tG\tA\t.\tPASS\t.\tGT\t0/1\n"

    def _make_zip(self, files: dict[str, str], compress_inner: bool = False) -> zipfile.ZipFile:
        """Create in-memory ZIP with VCF files."""
        buf = io.BytesIO()
        with zipfile.ZipFile(buf, "w") as zf:
            for name, content in files.items():
                data = content.encode()
                if compress_inner:
                    data = _gzip.compress(data)
                zf.writestr(name, data)
        buf.seek(0)
        return zipfile.ZipFile(buf, "r")

    def test_merges_two_vcfs(self):
        files = {
            "sample.chr1.vcf": self.VCF_HEADER + self.CHR1_DATA,
            "sample.chr2.vcf": self.VCF_HEADER + self.CHR2_DATA,
        }
        with self._make_zip(files) as zf:
            content = _merge_multi_vcf_zip(zf, list(files.keys()), "test-id")

        # Header should appear once
        assert content.count("##fileformat=VCFv4.2") == 1
        # All data lines present
        assert "rs1" in content
        assert "rs2" in content
        assert "rs3" in content

    def test_merges_gzipped_vcfs(self):
        files = {
            "sample.chr1.vcf.gz": self.VCF_HEADER + self.CHR1_DATA,
            "sample.chr2.vcf.gz": self.VCF_HEADER + self.CHR2_DATA,
        }
        with self._make_zip(files, compress_inner=True) as zf:
            content = _merge_multi_vcf_zip(zf, list(files.keys()), "test-id")

        assert content.count("##fileformat=VCFv4.2") == 1
        assert "rs1" in content
        assert "rs3" in content

    def test_sorts_by_chromosome(self):
        files = {
            "sample.chr2.vcf": self.VCF_HEADER + self.CHR2_DATA,
            "sample.chr1.vcf": self.VCF_HEADER + self.CHR1_DATA,
        }
        with self._make_zip(files) as zf:
            content = _merge_multi_vcf_zip(zf, list(files.keys()), "test-id")

        # chr1 data should come before chr2 data
        assert content.index("rs1") < content.index("rs3")

    def test_header_from_first_file_only(self):
        header2 = "##fileformat=VCFv4.2\n##source=different\n#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE\n"
        files = {
            "sample.chr1.vcf": self.VCF_HEADER + self.CHR1_DATA,
            "sample.chr2.vcf": header2 + self.CHR2_DATA,
        }
        with self._make_zip(files) as zf:
            content = _merge_multi_vcf_zip(zf, list(files.keys()), "test-id")

        # Only the beagle source header should be present
        assert "beagle" in content
        assert "different" not in content


# ---------------------------------------------------------------------------
# infer_biological_sex
# ---------------------------------------------------------------------------

def _make_sex_df(x_hom: int, x_het: int, y_count: int = 0) -> pl.DataFrame:
    """Build a minimal DataFrame with chrX/Y variants for sex inference tests."""
    rows = []
    for i in range(x_hom):
        rows.append({"rsid": f"rs_xh{i}", "chrom": "X", "position": i, "allele1": "A", "allele2": "A"})
    for i in range(x_het):
        rows.append({"rsid": f"rs_xv{i}", "chrom": "X", "position": 1000 + i, "allele1": "A", "allele2": "G"})
    for i in range(y_count):
        rows.append({"rsid": f"rs_y{i}", "chrom": "Y", "position": i, "allele1": "A", "allele2": "G"})
    return pl.DataFrame(rows, schema={"rsid": pl.Utf8, "chrom": pl.Utf8, "position": pl.Int64, "allele1": pl.Utf8, "allele2": pl.Utf8})


class TestInferBiologicalSex:
    def test_male_low_het(self):
        # 990 hom + 10 het on X → het rate 1% → male
        df = _make_sex_df(x_hom=990, x_het=10)
        assert infer_biological_sex(df) == "male"

    def test_female_high_het(self):
        # 750 hom + 250 het on X → het rate 25% → female
        df = _make_sex_df(x_hom=750, x_het=250)
        assert infer_biological_sex(df) == "female"

    def test_ambiguous_no_y_returns_none(self):
        # 850 hom + 150 het → 15% het rate (in ambiguous range), no Y variants
        df = _make_sex_df(x_hom=850, x_het=150, y_count=0)
        assert infer_biological_sex(df) is None

    def test_ambiguous_with_y_returns_male(self):
        # Ambiguous chrX, but Y variants present → male
        df = _make_sex_df(x_hom=850, x_het=150, y_count=10)
        assert infer_biological_sex(df) == "male"

    def test_insufficient_x_variants_returns_none(self):
        # Only 50 chrX variants — below minimum threshold
        df = _make_sex_df(x_hom=50, x_het=0)
        assert infer_biological_sex(df) is None

    def test_no_x_variants_returns_none(self):
        df = pl.DataFrame(
            {"rsid": ["rs1"], "chrom": ["1"], "position": [100], "allele1": ["A"], "allele2": ["G"]},
            schema={"rsid": pl.Utf8, "chrom": pl.Utf8, "position": pl.Int64, "allele1": pl.Utf8, "allele2": pl.Utf8},
        )
        assert infer_biological_sex(df) is None
