"""Tests for the genotype file parser."""

import pytest
import polars as pl

from app.services.parser import (
    ParseError,
    detect_chip_version,
    detect_format,
    parse_23andme,
    parse_ancestrydna,
    parse_cgi,
    parse_genotype_file,
    parse_vcf,
)

# ---------------------------------------------------------------------------
# Synthetic test data
# ---------------------------------------------------------------------------

SAMPLE_23ANDME = """\
# This data file generated by 23andMe at: Mon Jan 06 2025
# rsid\tchromosome\tposition\tgenotype
rs4477212\t1\t82154\tAA
rs3094315\t1\t752566\tAG
rs3131972\t1\t752721\tGG
rs12124819\t1\t776546\tAA
rs11240777\t1\t798959\tAG
rs6681049\t1\t800007\tCC
"""

SAMPLE_23ANDME_WITH_NOCALLS = """\
# rsid\tchromosome\tposition\tgenotype
rs4477212\t1\t82154\tAA
rs100\t1\t100\t--
rs200\t1\t200\t00
rs300\t1\t300\tDD
rs301\t1\t301\tDI
rs3094315\t1\t752566\tAG
"""

SAMPLE_23ANDME_HAPLOID = """\
# rsid\tchromosome\tposition\tgenotype
rs4477212\t1\t82154\tA
rs3094315\t1\t752566\tG
"""

SAMPLE_ANCESTRYDNA = """\
#AncestryDNA raw data download
#rsid\tchromosome\tposition\tallele1\tallele2
rs4477212\t1\t82154\tA\tA
rs3094315\t1\t752566\tA\tG
rs3131972\t1\t752721\tG\tG
rs12124819\t1\t776546\tA\tA
"""

SAMPLE_VCF = """\
##fileformat=VCFv4.1
##source=test
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE1
1\t82154\trs4477212\tA\tG\t100\tPASS\t.\tGT:GQ\t0/0:99
1\t752566\trs3094315\tA\tG\t100\tPASS\t.\tGT:GQ\t0/1:99
1\t752721\trs3131972\tA\tG\t100\tPASS\t.\tGT:GQ\t1/1:99
"""

SAMPLE_VCF_PHASED = """\
##fileformat=VCFv4.1
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE1
chr1\t82154\trs4477212\tA\tG\t100\tPASS\t.\tGT\t0|1
"""

SAMPLE_VCF_MULTIALLELIC = """\
##fileformat=VCFv4.1
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE1
1\t82154\trs4477212\tA\tG,T\t100\tPASS\t.\tGT\t0/1
1\t752566\trs3094315\tA\tG\t100\tPASS\t.\tGT\t0/1
"""

# Haploid genotypes on sex chromosomes (male chrX/chrY)
SAMPLE_VCF_HAPLOID = """\
##fileformat=VCFv4.1
#CHROM\tPOS\tID\tREF\tALT\tQUAL\tFILTER\tINFO\tFORMAT\tSAMPLE1
X\t43591036\trs6323\tG\tT\t40\tPASS\t.\tGT:GQ\t1:99
X\t100000\trs99999\tC\tA\t50\tPASS\t.\tGT:GQ\t0:99
1\t752566\trs3094315\tA\tG\t100\tPASS\t.\tGT:GQ\t0/1:99
"""

# Complete Genomics var-ASM format:
# - Two rows per diploid variant (one per allele)
# - 0-based half-open coordinates (begin+1 = 1-based position)
# - rsIDs in xRef column as "dbsnp.NNN:rsXXXXXX"
# Locus 10: homozygous alt T/T (both alleles are SNP)
# Locus 20: het allele1=A (SNP), allele2=ref G (no SNP row)
# Locus 30: het allele1=ref A (no SNP row), allele2=G (SNP)
# Locus 40: VQLOW — should be filtered out
SAMPLE_CGI = """\
#ASSEMBLY_ID\tGS00253-DNA_A01_200_37-ASM
#GENOME_REFERENCE\tNCBI build 37
#TYPE\tVAR-ANNOTATION
\t\t\t\t\t\t\t\t\t\t\t\t\t
>locus\tploidy\tallele\tchromosome\tbegin\tend\tvarType\treference\talleleSeq\tvarScoreVAF\tvarScoreEAF\tvarQuality\thapLink\txRef
10\t2\t1\tchr1\t21579\t21580\tsnp\tC\tT\t100\t100\tVQHIGH\t\tdbsnp.83:rs526642
10\t2\t2\tchr1\t21579\t21580\tsnp\tC\tT\t135\t135\tVQHIGH\t\tdbsnp.83:rs526642
20\t2\t1\tchr1\t23974\t23975\tsnp\tG\tA\t58\t58\tVQHIGH\t\tdbsnp.100:rs2748067;dbsnp.131:rs76046194
30\t2\t2\tchr19\t38231\t38232\tsnp\tA\tG\t112\t112\tVQHIGH\t\tdbsnp.86:rs806727
40\t2\t1\tchr1\t46669\t46670\tsnp\tA\tG\t45\t45\tVQLOW\t\tdbsnp.100:rs2548905
"""


# ---------------------------------------------------------------------------
# Format detection
# ---------------------------------------------------------------------------

class TestDetectFormat:
    def test_detects_23andme(self):
        lines = SAMPLE_23ANDME.split("\n")[:10]
        assert detect_format(lines) == "23andme"

    def test_detects_ancestrydna(self):
        lines = SAMPLE_ANCESTRYDNA.split("\n")[:10]
        assert detect_format(lines) == "ancestrydna"

    def test_detects_vcf(self):
        lines = SAMPLE_VCF.split("\n")[:10]
        assert detect_format(lines) == "vcf"

    def test_detects_cgi(self):
        lines = SAMPLE_CGI.split("\n")[:10]
        assert detect_format(lines) == "cgi"

    def test_raises_on_unknown(self):
        with pytest.raises(ParseError):
            detect_format(["some random text", "with no structure"])


# ---------------------------------------------------------------------------
# 23andMe parser
# ---------------------------------------------------------------------------

class TestParse23andMe:
    def test_basic_parsing(self):
        df = parse_23andme(SAMPLE_23ANDME)
        assert len(df) == 6
        assert df.columns == ["rsid", "chrom", "position", "allele1", "allele2"]

    def test_specific_variant(self):
        df = parse_23andme(SAMPLE_23ANDME)
        row = df.filter(pl.col("rsid") == "rs3094315")
        assert row["allele1"][0] == "A"
        assert row["allele2"][0] == "G"
        assert row["chrom"][0] == "1"
        assert row["position"][0] == 752566

    def test_homozygous(self):
        df = parse_23andme(SAMPLE_23ANDME)
        row = df.filter(pl.col("rsid") == "rs4477212")
        assert row["allele1"][0] == "A"
        assert row["allele2"][0] == "A"

    def test_filters_nocalls(self):
        df = parse_23andme(SAMPLE_23ANDME_WITH_NOCALLS)
        assert len(df) == 2
        rsids = df["rsid"].to_list()
        assert "rs4477212" in rsids
        assert "rs3094315" in rsids

    def test_haploid_genotype(self):
        df = parse_23andme(SAMPLE_23ANDME_HAPLOID)
        assert len(df) == 2
        row = df.filter(pl.col("rsid") == "rs4477212")
        assert row["allele1"][0] == "A"
        assert row["allele2"][0] == "A"

    def test_empty_file_raises(self):
        with pytest.raises(ParseError):
            parse_23andme("# comment only\n")

    def test_dtypes(self):
        df = parse_23andme(SAMPLE_23ANDME)
        assert df.schema["rsid"] == pl.Utf8
        assert df.schema["chrom"] == pl.Utf8
        assert df.schema["position"] == pl.Int64
        assert df.schema["allele1"] == pl.Utf8
        assert df.schema["allele2"] == pl.Utf8


# ---------------------------------------------------------------------------
# AncestryDNA parser
# ---------------------------------------------------------------------------

class TestParseAncestryDNA:
    def test_basic_parsing(self):
        df = parse_ancestrydna(SAMPLE_ANCESTRYDNA)
        assert len(df) == 4
        assert df.columns == ["rsid", "chrom", "position", "allele1", "allele2"]

    def test_specific_variant(self):
        df = parse_ancestrydna(SAMPLE_ANCESTRYDNA)
        row = df.filter(pl.col("rsid") == "rs3094315")
        assert row["allele1"][0] == "A"
        assert row["allele2"][0] == "G"
        assert row["position"][0] == 752566

    def test_empty_file_raises(self):
        with pytest.raises(ParseError):
            parse_ancestrydna("# comment only\n")


# ---------------------------------------------------------------------------
# VCF parser
# ---------------------------------------------------------------------------

class TestParseVCF:
    def test_basic_parsing(self):
        df = parse_vcf(SAMPLE_VCF)
        assert len(df) == 3

    def test_homref(self):
        df = parse_vcf(SAMPLE_VCF)
        row = df.filter(pl.col("rsid") == "rs4477212")
        assert row["allele1"][0] == "A"
        assert row["allele2"][0] == "A"

    def test_het(self):
        df = parse_vcf(SAMPLE_VCF)
        row = df.filter(pl.col("rsid") == "rs3094315")
        assert row["allele1"][0] == "A"
        assert row["allele2"][0] == "G"

    def test_homalt(self):
        df = parse_vcf(SAMPLE_VCF)
        row = df.filter(pl.col("rsid") == "rs3131972")
        assert row["allele1"][0] == "G"
        assert row["allele2"][0] == "G"

    def test_phased_genotype(self):
        df = parse_vcf(SAMPLE_VCF_PHASED)
        assert len(df) == 1
        row = df.row(0, named=True)
        assert row["allele1"] == "A"
        assert row["allele2"] == "G"
        # chr prefix should be stripped
        assert row["chrom"] == "1"

    def test_skips_multiallelic(self):
        df = parse_vcf(SAMPLE_VCF_MULTIALLELIC)
        assert len(df) == 1
        assert df["rsid"][0] == "rs3094315"

    def test_haploid_hemizygous_alt(self):
        """Hemizygous ALT on chrX (e.g. rs6323 MAOA in males) should be duplicated."""
        df = parse_vcf(SAMPLE_VCF_HAPLOID)
        row = df.filter(pl.col("rsid") == "rs6323")
        assert len(row) == 1
        assert row["allele1"][0] == "T"
        assert row["allele2"][0] == "T"
        assert row["chrom"][0] == "X"

    def test_haploid_hemizygous_ref(self):
        """Hemizygous REF on chrX should be duplicated."""
        df = parse_vcf(SAMPLE_VCF_HAPLOID)
        row = df.filter(pl.col("rsid") == "rs99999")
        assert len(row) == 1
        assert row["allele1"][0] == "C"
        assert row["allele2"][0] == "C"

    def test_haploid_mixed_with_diploid(self):
        """Haploid and diploid calls in same VCF should both be parsed."""
        df = parse_vcf(SAMPLE_VCF_HAPLOID)
        assert len(df) == 3  # 2 haploid + 1 diploid

    def test_empty_file_raises(self):
        with pytest.raises(ParseError):
            parse_vcf("##fileformat=VCFv4.1\n#CHROM\tPOS\tID\n")


# ---------------------------------------------------------------------------
# Complete Genomics parser
# ---------------------------------------------------------------------------

class TestParseCGI:
    def test_basic_parsing(self):
        df = parse_cgi(SAMPLE_CGI)
        assert df.columns == ["rsid", "chrom", "position", "allele1", "allele2"]
        # 3 variants: locus 10 (hom), locus 20 (het a1), locus 30 (het a2)
        # Locus 40 filtered out (VQLOW)
        assert len(df) == 3

    def test_homozygous_alt(self):
        """Locus 10: both alleles are SNP T (ref C)."""
        df = parse_cgi(SAMPLE_CGI)
        row = df.filter(pl.col("rsid") == "rs526642")
        assert row["allele1"][0] == "T"
        assert row["allele2"][0] == "T"

    def test_het_allele1_only(self):
        """Locus 20: only allele 1 is a SNP (A), allele 2 should be ref (G)."""
        df = parse_cgi(SAMPLE_CGI)
        row = df.filter(pl.col("rsid") == "rs2748067")
        assert row["allele1"][0] == "A"
        assert row["allele2"][0] == "G"

    def test_het_allele2_only(self):
        """Locus 30: only allele 2 is a SNP (G), allele 1 should be ref (A)."""
        df = parse_cgi(SAMPLE_CGI)
        row = df.filter(pl.col("rsid") == "rs806727")
        assert row["allele1"][0] == "A"
        assert row["allele2"][0] == "G"

    def test_filters_vqlow(self):
        """Locus 40 is VQLOW and should be excluded."""
        df = parse_cgi(SAMPLE_CGI)
        assert df.filter(pl.col("rsid") == "rs2548905").height == 0

    def test_position_conversion(self):
        """CGI 0-based begin=21579 should become 1-based position=21580."""
        df = parse_cgi(SAMPLE_CGI)
        row = df.filter(pl.col("rsid") == "rs526642")
        assert row["position"][0] == 21580

    def test_chr_prefix_stripped(self):
        df = parse_cgi(SAMPLE_CGI)
        row = df.filter(pl.col("rsid") == "rs806727")
        assert row["chrom"][0] == "19"

    def test_extracts_first_rsid_from_multi(self):
        """xRef with multiple dbsnp entries should extract the first rsID."""
        df = parse_cgi(SAMPLE_CGI)
        # Locus 20 has "dbsnp.100:rs2748067;dbsnp.131:rs76046194"
        assert df.filter(pl.col("rsid") == "rs2748067").height == 1

    def test_empty_file_raises(self):
        with pytest.raises(ParseError):
            parse_cgi("#TYPE\tVAR-ANNOTATION\n>locus\tploidy\tallele\n")

    def test_dtypes(self):
        df = parse_cgi(SAMPLE_CGI)
        assert df.schema["rsid"] == pl.Utf8
        assert df.schema["chrom"] == pl.Utf8
        assert df.schema["position"] == pl.Int64
        assert df.schema["allele1"] == pl.Utf8
        assert df.schema["allele2"] == pl.Utf8


# ---------------------------------------------------------------------------
# Chip version detection
# ---------------------------------------------------------------------------

class TestDetectChipVersion:
    def test_23andme_v5(self):
        assert detect_chip_version(950_000) == "23andme_v5"

    def test_ancestrydna_v2(self):
        assert detect_chip_version(350_000) == "ancestrydna_v2"

    def test_unknown(self):
        assert detect_chip_version(50) == "unknown"


# ---------------------------------------------------------------------------
# Integration: parse_genotype_file
# ---------------------------------------------------------------------------

class TestParseGenotypeFile:
    def test_23andme_integration(self):
        df, fmt, chip = parse_genotype_file(SAMPLE_23ANDME)
        assert fmt == "23andme"
        assert len(df) == 6
        assert chip == "unknown"  # too few variants for chip detection

    def test_ancestrydna_integration(self):
        df, fmt, chip = parse_genotype_file(SAMPLE_ANCESTRYDNA)
        assert fmt == "ancestrydna"
        assert len(df) == 4

    def test_vcf_integration(self):
        df, fmt, chip = parse_genotype_file(SAMPLE_VCF)
        assert fmt == "vcf"
        assert len(df) == 3

    def test_cgi_integration(self):
        df, fmt, chip = parse_genotype_file(SAMPLE_CGI)
        assert fmt == "cgi"
        assert len(df) == 3

    def test_filters_indels_from_23andme(self):
        content = """\
# rsid\tchromosome\tposition\tgenotype
rs100\t1\t100\tAG
rs200\t1\t200\tDI
rs300\t1\t300\tAA
"""
        df, fmt, _ = parse_genotype_file(content)
        assert len(df) == 2
